package com.i2g.rms.rest.service;

import java.util.Objects;

import com.i2g.rms.service.message.MessageKey;
import com.i2g.rms.service.message.MessageProducer;

/**
 * Enumeration to define message constants for the common error messages in
 * REST end points.
 *
 * @since 1.0.0
 * @author Karthikeyan Chidambaram
 * @author RMS Development Team
 */
public enum RestMessage implements MessageKey {
	
	TEST_ERROR_MESSAGE(1001),
	DEPT_NO_NULL_OR_EMPTY(1002),
	DEPT_NAME_NULL_OR_EMPTY(1003),
	DEPT_LOC_NULL_OR_EMPTY(1004),
	INVALID_REQUEST_BODY(1005),
	DEPT_DOES_NOT_EXIST(1006),
	LOGIN_REQ_BODY_NULL_OR_EMPTY(1007),
	USER_LOGIN_ID_NULL_OR_EMPTY(1008),
	PASSWORD_NULL_OR_EMPTY(1009),
	INVALID_SESSION(1010),
	
	/** Table Maintenance Error Codes */
	INPUT_OBJECT_NULL_OR_EMPTY(1011),
	CODE_NULL_OR_EMPTY(1012),
	DESCRIPTION_NULL_OR_EMPTY(1013),
	TABLE_NAME_NULL_OR_EMPTY(1014),
	OPERATION_NULL_OR_EMPTY(1015),
	OBJECT_ARRAY_NULL_OR_EMPTY(1016),
	CREATE_TABLE_MAINTENANCE_RECORD_FAILED(1017),
	DELETE_OPERATION_FAILED(1018),
	NOT_ALL_RECORDS_WERE_DELETED(1019),
	CREDENTIALS_NOT_PRESENT_IN_REQUEST(1020),
	REQUEST_OBJECT_NULL_OR_EMPTY(1021),
	UNIQUE_INCIDENT_ID_NULL_OR_EMPTY(1022),
	PARENT_CODE_NULL_OR_EMPTY(1023),
	PARENT_OBJECT_NULL_OR_EMPTY(1024),	
	OBJECT_NULL_OR_EMPTY(1025),
	UNABLE_TO_CREATE_RECORD(1026),
	UNABLE_TO_FETCH_USER_DETAILS(1027),
	CONFLICT_BETWEEN_INCIDENT_REPORTED_BY_AND_LOGGED_IN_USER(1028),
	UNABLE_TO_UPDATE_RECORD(1029),
	WEAPON_TYPE_NOT_APPLICABLE_WITHOUT_WEAPON_INVOLVED(1030),
	WEAPON_TYPE_MUST_BE_SPECIFIED_WHEN_WEAPON_INVOLVED(1031),
	EXTERNAL_AGENCY_NOT_APPLICABLE_WITHOUT_AGENCY_CONTACTED(1032),
	EXTERNAL_AGENCY_MUST_BE_SPECIFIED_WHEN_AGENCY_CONTACTED(1033),
	EXTERNAL_AGENCY_DATE_TIME_MUST_BE_SPECIFIED_WHEN_AGENCY_CONTACTED(1034),
	EXTERNAL_AGENCY_DATE_TIME_NOT_APPLICABLE_WITHOUT_AGENCY_CONTACTED(1035),
	UNABLE_TO_FETCH_UPDATED_RECORD(1036),
	WITNESS_FLAG_MUST_BE_NO(1037),
	WITNESS_FLAG_MUST_BE_YES(1038),
	UNABLE_TO_PARSE_ONE_OR_MORE_INPUT_PARAMS(1039),
	FILE_UPLOAD_VALIDATION_ERROR(1040),
	FILE_UPLOAD_PARAMETERS_DOES_NOT_MATCH(1041),
	ERROR_WHILE_PARSING_FILE_BEFORE_UPLOAD(1042),
	INVALID_KEY_PASSED_FOR_DELETE(1043),
	NOTHING_TO_DELETE(1044),
	GENERIC_DOWNLOAD_ERROR_MESSAGE(1045),
	IOEXCEPTION_WHILE_FILE_DOWNLOAD(1046),
	UNABLE_TO_FETCH_FILE_FOR_DOWNLOAD(1047),
	GENERIC_FETCH_FAILED_MESSAGE(1048),
	INPUT_STRING_NULL_OR_EMPTY(1049),
	RECORD_FETCH_FAILED_FOR_UPDATE(1050),
	UNABLE_TO_CONSTRUCT_OBJECT_FOR_RECORD_CREATION(1051),
	INVALID_SUSPECT_ID_PASSED_AS_PARAMETER(1052),
	UNIQUE_INCIDENT_ID_AND_SUSPECT_ID_DOES_NOT_MATCH(1053),
	UNABLE_TO_ADD_SUSPECT_TO_INCIDENT(1054),
	NO_RECORDS_WERE_DELETED(1055),
	UNABLE_TO_BUILD_OBJECT_OR_COLLECTION(1056),
	INCIDENT_ALREADY_HAS_EXISTING_ACCIDENT_RECORD(1057),
	INCIDENT_ALREADY_HAS_EXISTING_ASSET_RECORD(1058),
	INVALID_CRIME_SUSPECT_ID_PASSED_AS_PARAMETER(1059),
	CRIME_ID_AND_CRIME_SUSPECT_ID_DOES_NOT_MATCH(1060),	
	INCIDENT_ALREADY_HAS_EXISTING_CLAIM_RECORD(1061),
	INCIDENT_ALREADY_SUBMITTED(1062),
	INCIDENT_ALREADY_HAS_EXISTING_INVESTIGATION_RECORD(1063);
	
	/** Primary key ID of Rest Message ID entity in persistent store for retrieval. */
	private final Integer _id;

	/**
	 * Creates a new enum {@code RestMessageId} constant with the specified
	 * {@code id}.
	 *
	 * @param id of message entity
	 */
	private RestMessage(final Integer id) {
		_id = Objects.requireNonNull(id, "REST Message ID cannot be null");
	}

	@Override
	public Integer getKey() {
		return _id;
	}

	@Override
	public String getName() {
		return name();
	}

	@Override
	public int getArgsCount() {
		return -1;
	}

	@Override
	public MessageProducer getBuilder() {
		return MessageProducer.STANDARD_BUILDER;
	}
}
